services:
  amigo:
    build:
      context: .
      dockerfile: docker/Dockerfile.amigo
    image: amigo
    restart: always
    healthcheck:
      test: ["CMD", "timeout", "1", "bash", "-c", "cat < /dev/null > /dev/tcp/localhost/9999"]
      start_period: 1s
    ports:
      - "8011:9999"

  golr:
    build:
      context: .
      dockerfile: docker/Dockerfile.golr
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--head", "--fail", "--silent", "--output", "/dev/null", "http://localhost:8080"]
      start_period: 5s
    ports:
      - "8010:8080"

  load:
    image: amigo
    pull_policy: never
    depends_on:
      amigo:
        condition: service_started
      golr:
        condition: service_healthy 
    entrypoint: ["npx", "gulp", "load-ontology-purge-safe"]
